turtlesUI:
  enabled: false
  version: v0.8.2
rancherTurtles:
  image: registry.rancher.com/rancher/rancher/turtles
  imageVersion: v0.17.0
  imagePullPolicy: IfNotPresent
  namespace: rancher-turtles-system
  managerArguments: []
  imagePullSecrets: []
  rancherInstalled: false
  kubectlImage: registry.suse.com/edge/3.2/kubectl:1.30.3
  features:
    day2operations:
      enabled: false
      image: registry.rancher.com/rancher/rancher/turtles
      imageVersion: v0.17.0
      imagePullPolicy: IfNotPresent
      etcdBackupRestore:
        enabled: false
    # beta feature, see documentation for more information on feature stages
    addon-provider-fleet:
      enabled: true
    # alpha feature, see documentation for more information on feature stages
    agent-tls-mode:
      enabled: false
    clusterclass-operations:
      enabled: false
      image: registry.rancher.com/rancher/rancher/turtles
      imageVersion: v0.17.0
      imagePullPolicy: IfNotPresent
cluster-api-operator:
  enabled: true
  cert-manager:
    enabled: false
  volumes:
    - name: cert
      secret:
        defaultMode: 420
        secretName: capi-operator-webhook-service-cert
    - name: clusterctl-config
      configMap:
        name: clusterctl-config
  image:
    manager:
      repository: registry.rancher.com/rancher/cluster-api-operator
  volumeMounts:
    manager:
      - mountPath: /tmp/k8s-webhook-server/serving-certs
        name: cert
        readOnly: true
      - mountPath: /config
        name: clusterctl-config
        readOnly: true
  cleanup: true
  cluster-api:
    enabled: true
    configSecret:
      name: ""
      defaultName: capi-env-variables
    core:
      namespace: capi-system
      imageUrl: ""
      fetchConfig:
        url: ""
        selector: ""
    rke2:
      enabled: true
      version: ""
      bootstrap:
        namespace: rke2-bootstrap-system
        imageUrl: ""
        fetchConfig:
          url: ""
          selector: ""
      controlPlane:
        namespace: rke2-control-plane-system
        imageUrl: ""
        fetchConfig:
          url: ""
          selector: ""
    metal3:
      enabled: true
      version: "v1.9.3"
      infrastructure:
        namespace: capm3-system
        imageUrl: "registry.suse.com/rancher/cluster-api-provider-metal3:v1.9.3"
        fetchConfig:
          url: ""
          selector: ""
      ipam:
        namespace: capm3-system
        imageUrl: "registry.suse.com/rancher/ip-address-manager:v1.9.4"
