annotations:
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-sriov-system
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/release-name: sriov-crd
apiVersion: v2
appVersion: v1.5.0
description: Installs the CRDs for the SR-IOV operator
name: sriov-crd
type: application
version: 1.5.1+up1.5.0
