apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "upgrade-controller.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "upgrade-controller.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "upgrade-controller.certificate" . }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "upgrade-controller.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-lifecycle-suse-com-v1alpha1-upgradeplan
    failurePolicy: Fail
    name: upgrade-plan-policy.suse.com
    rules:
      - apiGroups:
          - lifecycle.suse.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - upgradeplans
    sideEffects: None
