apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "endpoint-copier-operator.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "endpoint-copier-operator.selectorLabels" . | nindent 6 }}
