kubevirt:
  image: registry.suse.com/suse/sles/15.5/virt-operator
  version: 1.1.0-150500.8.6.1
  pullPolicy: IfNotPresent

securityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

namespaceHook: kubevirt-namespace-modify
namespaceHookType: pre-install

crdUpgradeHook: kubevirt-crd-upgrade
crdUpgradeHookType: pre-upgrade

crUninstallHook: kubevirt-uninstall
crUninstallHookType: pre-delete

crdUninstallHook: kubevirt-crd-uninstall
crdUninstallHookType: post-delete

hookImage: bitnami/kubectl:1.27.3
hookRestartPolicy: OnFailure
hookDeletePolicy: before-hook-creation,hook-succeeded
