{{- $secret_name := include "powerdns.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
type: Opaque
data:
  api-key: "{{ .Values.powerdns.api.key | toString | b64enc }}"
  # Check if the secret is deployed and has a password
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  {{- if and $old_sec (index $old_sec.data "webserver-password") }}
  webserver-password: {{ index $old_sec.data "webserver-password" }}
  {{- else if .Values.powerdns.webserver.password }}
  # If not, check if a password is provided in values.yaml
  webserver-password: {{ .Values.powerdns.webserver.password | toString | b64enc }}
  {{- else }}
  # If no secret and no password in values.yaml, generate a new password
  webserver-password: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
