annotations:
  catalog.cattle.io/auto-install: sriov-crd=match
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/namespace: cattle-sriov-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/upstream-version: 1.5.0
apiVersion: v2
appVersion: v1.5.0
dependencies:
- condition: sriov-nfd.enabled
  name: sriov-nfd
  repository: file://./charts/sriov-nfd
  version: 0.15.7
description: SR-IOV network operator configures and manages SR-IOV networks in the
  kubernetes cluster
home: https://github.com/k8snetworkplumbingwg/sriov-network-operator
icon: https://charts.rancher.io/assets/logos/sr-iov.svg
keywords:
- sriov
kubeVersion: '>= 1.24.0-0'
name: sriov-network-operator
sources:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator
type: application
version: 1.5.2+up1.5.0
