{{- if index .Values "cluster-api-operator" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterctl-config
  namespace: '{{ .Values.rancherTurtles.namespace }}'
data:
  clusterctl.yaml: |
    images:
      all:
        repository: registry.suse.com/edge
    providers:
      # Cluster API core provider
      - name:         "cluster-api"
        url:          "https://github.com/kubernetes-sigs/cluster-api/releases/v1.6.2/core-components.yaml"
        type:         "CoreProvider"

      # Infrastructure providers
      - name:         "metal3"
        url:          "https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.6.0/infrastructure-components.yaml"
        type:         "InfrastructureProvider"

      # Bootstrap providers
      - name:         "rke2"
        url:          "https://github.com/rancher-sandbox/cluster-api-provider-rke2/releases/download/v0.2.6/bootstrap-components.yaml"
        type:         "BootstrapProvider"

      # ControlPlane providers
      - name:         "rke2"
        url:          "https://github.com/rancher-sandbox/cluster-api-provider-rke2/releases/download/v0.2.6/control-plane-components.yaml"
        type:         "ControlPlaneProvider"

    # Addon providers
    #- name:         "fleet"
    #  url:          "https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet/releases/latest/addon-components.yaml"
    #  type:         "AddonProvider"
{{- end }}