apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: kubevirt-crd-manifest
  annotations:
    "helm.sh/hook": {{ .Values.crdUpgradeHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "1"
data:
  crd: |-
    {{ $.Files.Get "crds/kubevirt.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.crdUpgradeHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUpgradeHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.crdUpgradeHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUpgradeHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "2"
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames:
      - "kubevirt-crd-manifest"
    verbs: [ "get" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    resourceNames:
      - "kubevirts.kubevirt.io"
    verbs: [ "get", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.crdUpgradeHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUpgradeHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "3"
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.crdUpgradeHook }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.crdUpgradeHook }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.crdUpgradeHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUpgradeHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "4"
spec:
  template:
    metadata:
      name: {{ .Values.crdUpgradeHook }}
    spec:
      serviceAccountName: {{ .Values.crdUpgradeHook }}
      restartPolicy: {{ .Values.hookRestartPolicy }}
      containers:
        - name: {{ .Values.crdUpgradeHook }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.hookImage }}
          command:
            - /bin/sh
            - -c
            - >
              kubectl get configmap kubevirt-crd-manifest -o "jsonpath={.data['crd']}" | kubectl apply -f -;
