apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.kubevirt.certificateRotateStrategy }}
  certificateRotateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubevirt.configuration }}
  configuration:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubevirt.customizeComponents }}
  customizeComponents:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  imagePullPolicy: {{ .Values.kubevirt.pullPolicy }}
  {{- with .Values.kubevirt.workloadUpdateStrategy }}
  workloadUpdateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
