apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-crd-uninstall
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubevirt-crd-uninstall
  name: kubevirt-crd-uninstaller
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-crd-uninstaller
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    resourceNames:
      - "kubevirts.kubevirt.io"
    verbs: [ "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-crd-uninstaller
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
subjects:
  - kind: ServiceAccount
    namespace: kubevirt-crd-uninstall
    name: kubevirt-crd-uninstaller
roleRef:
  kind: ClusterRole
  name: kubevirt-crd-uninstaller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kubevirt-crd-uninstall
  name: kubevirt-crd-uninstaller
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "4"
spec:
  template:
    metadata:
      name: kubevirt-crd-uninstaller
    spec:
      serviceAccountName: kubevirt-crd-uninstaller
      restartPolicy: OnFailure
      containers:
        - name: kubevirt-crd-uninstaller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.kubecli.image }}
          command:
            - /bin/sh
            - -c
            - >
              kubectl delete customresourcedefinitions kubevirts.kubevirt.io;
