apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.crdUninstallHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUninstallHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.crdUninstallHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUninstallHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    resourceNames:
      - "kubevirts.kubevirt.io"
    verbs: [ "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.crdUninstallHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUninstallHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "2"
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.crdUninstallHook }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.crdUninstallHook }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.crdUninstallHook }}
  annotations:
    "helm.sh/hook": {{ .Values.crdUninstallHookType }}
    "helm.sh/hook-delete-policy": {{ .Values.hookDeletePolicy }}
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: {{ .Values.crdUninstallHook }}
    spec:
      serviceAccountName: {{ .Values.crdUninstallHook }}
      restartPolicy: {{ .Values.hookRestartPolicy }}
      containers:
        - name: {{ .Values.crdUninstallHook }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.hookImage }}
          command:
            - /bin/sh
            - -c
            - >
              kubectl delete customresourcedefinitions kubevirts.kubevirt.io;
