apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubevirt
  name: kubevirt-cr-uninstaller
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubevirt
  name: kubevirt-cr-uninstaller
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [ "kubevirt.io" ]
    resources: [ "kubevirts" ]
    resourceNames:
      - "kubevirt"
    verbs: [ "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kubevirt
  name: kubevirt-cr-uninstaller
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
subjects:
  - kind: ServiceAccount
    namespace: kubevirt
    name: kubevirt-cr-uninstaller
roleRef:
  kind: Role
  name: kubevirt-cr-uninstaller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kubevirt
  name: kubevirt-cr-uninstaller
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: kubevirt-cr-uninstaller
    spec:
      serviceAccountName: kubevirt-cr-uninstaller
      restartPolicy: OnFailure
      containers:
        - name: kubevirt-cr-uninstaller
          image: {{ .Values.kubecli.image }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - /bin/sh
            - -c
            - >
              kubectl delete kubevirt kubevirt;
              sleep 45; # wait for the operator to clean up
