apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: kubevirt-namespace-modifier
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-namespace-modifier
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames:
      - {{ .Release.Namespace | quote }}
    verbs: [ "get", "patch" ]
  - apiGroups: [ "management.cattle.io" ] # Rancher
    resources: [ "projects" ]
    verbs: [ "updatepsa" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-namespace-modifier
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: kubevirt-namespace-modifier
roleRef:
  kind: ClusterRole
  name: kubevirt-namespace-modifier
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: kubevirt-namespace-modifier
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: kubevirt-namespace-modifier
    spec:
      serviceAccountName: kubevirt-namespace-modifier
      restartPolicy: OnFailure
      containers:
        - name: kubevirt-namespace-modifier
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.kubecli.image }}
          command:
            - /bin/sh
            - -c
            - >
              kubectl label namespace {{ .Release.Namespace }} kubevirt.io="";
              kubectl label namespace {{ .Release.Namespace }} pod-security.kubernetes.io/enforce="privileged";
