{{- if and (.Values.serviceAccount.create) (.Values.global.enable_ironic) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ironic.serviceAccountName" . }}
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
