cdi:
  version: 1.58.0-150500.6.6.1
  operatorImage: registry.suse.com/suse/sles/15.5/cdi-operator
  controllerImage: registry.suse.com/suse/sles/15.5/cdi-controller
  importerImage: registry.suse.com/suse/sles/15.5/cdi-importer
  clonerImage: registry.suse.com/suse/sles/15.5/cdi-cloner
  apiserverImage: registry.suse.com/suse/sles/15.5/cdi-apiserver
  uploadserverImage: registry.suse.com/suse/sles/15.5/cdi-uploadserver
  uploadproxyImage: registry.suse.com/suse/sles/15.5/cdi-uploadproxy
  pullPolicy: IfNotPresent

kubecli:
  image: bitnami/kubectl:1.27.3
