rancherTurtles:
  image: registry.rancher.com/rancher/rancher/turtles
  imageVersion: sha256:4a56a3b33a59ba5ed864b950aa4546e7bc5165c24da12d48690fe29bdb94d9cc
  imagePullPolicy: IfNotPresent
  namespace: rancher-turtles-system
  managerArguments: []
  imagePullSecrets: []
  features:
    cluster-api-operator:
      cleanup: true
      kubectlImage: registry.k8s.io/kubernetes/kubectl:v1.28.0
    embedded-capi:
      disabled: true
    rancher-webhook:
      cleanup: true
      kubectlImage: registry.k8s.io/kubernetes/kubectl:v1.28.0
    rancher-kubeconfigs:
      label: true
    managementv3-cluster:
      enabled: true
    managementv3-cluster-migration:
      enabled: false
    propagate-labels:
      enabled: false
    etcd-snapshot-restore:
      enabled: false
    addon-provider-fleet:
      enabled: false
cluster-api-operator:
  enabled: true
  cert-manager:
    enabled: false
  volumes:
    - name: cert
      secret:
        defaultMode: 420
        secretName: capi-operator-webhook-service-cert
    - name: clusterctl-config
      configMap:
        name: clusterctl-config
  volumeMounts:
    manager:
      - mountPath: /tmp/k8s-webhook-server/serving-certs
        name: cert
        readOnly: true
      - mountPath: /config
        name: clusterctl-config
        readOnly: true
  cluster-api:
    enabled: true
    configSecret:
      name: ""
      defaultName: capi-env-variables
    core:
      namespace: capi-system
      imageUrl: ""
      fetchConfig:
        url: ""
        selector: ""
    rke2:
      enabled: true
      version: ""
      bootstrap:
        namespace: rke2-bootstrap-system
        imageUrl: ""
        fetchConfig:
          url: ""
          selector: ""
      controlPlane:
        namespace: rke2-control-plane-system
        imageUrl: ""
        fetchConfig:
          url: ""
          selector: ""
    metal3:
      enabled: true
      version: ""
      infrastructure:
        namespace: capm3-system
        imageUrl: ""
        fetchConfig:
          url: ""
          selector: ""
