url: https://github.com/kubernetes-sigs/cluster-api-operator/releases/download/v0.17.0/cluster-api-operator-0.17.0.tgz
version: 0.17.0
# cluster-api-operator is only used as a dependency of rancher-turtles
doNotRelease: true
