name: Test Charts Pull Request

on:
  pull_request:

jobs:
  test-charts-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Validate charts
      run: |
        make validate
